package-name: terrafomo-aws
provider-name: AWS

extra-deps:
  - amazonka-core
  - formatting
  - iproute
  - amazonka-iam-policy >= 0.0.4

field-overrides:
  # Provider

  Provider:
    region: 'P.Region'

  AssumeRoleSetting:
    policy: 'P.Maybe P.Document'

  # Resources

  IamRoleResource:
    assumeRolePolicy: 'TF.Attr s P.Document'

  IamRolePolicyResource:
    policy: 'TF.Attr s P.Document'

  IamPolicyResource:
    policy: 'TF.Attr s P.Document'

  IamGroupPolicyResource:
    policy: 'TF.Attr s P.Document'

  S3BucketResource:
    region: 'TF.Attr s P.Region'

  SecurityGroupRuleResource:
    type': 'TF.Attr s P.NetworkTraffic'
    protocol: 'TF.Attr s P.NetworkProtocol'
    cidrBlocks: 'TF.Attr s [TF.Attr s P.IPRange]'
    ipv6CidrBlocks: 'TF.Attr s [TF.Attr s P.IPRange]'

  VpcResource:
    cidrBlock: 'TF.Attr s P.IPRange'

  SubnetResource:
    cidrBlock: 'TF.Attr s P.IPRange'
    availabilityZone: 'TF.Attr s P.Zone'

  RouteResource:
    destinationCidrBlock: 'TF.Attr s P.IPRange'
    destinationIpv6CidrBlock: 'TF.Attr s P.IPRange'

  # Settings

  DynamodbTableAttribute:
    type': 'TF.Attr s P.TableAttributeType'
